name: Build Android APK and Windows EXE

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Android APK (universal)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: react_to_tap-android-apk
          path: build/app/outputs/flutter-apk/react_to_tap.apk

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Windows (Release)
        run: flutter build windows --release

      - name: Archive Windows Build
        run: |
          powershell -Command "Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath react_to_tap-windows.zip"

      - name: Upload Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: react_to_tap-windows-zip
          path: react_to_tap-windows.zip
